topics:
  # Custom message
  - name: "/robot_status"
    type: "demo_msgs/msg/RobotStatus"
    qos_depth: 10

  # sensor_msgs
  - name: "/battery_state"
    type: "sensor_msgs/msg/BatteryState"
    qos_depth: 10
  - name: "/camera_info"
    type: "sensor_msgs/msg/CameraInfo"
    qos_depth: 10
  - name: "/channel_float32"
    type: "sensor_msgs/msg/ChannelFloat32"
    qos_depth: 10
  - name: "/compressed_image"
    type: "sensor_msgs/msg/CompressedImage"
    qos_depth: 10
  - name: "/fluid_pressure"
    type: "sensor_msgs/msg/FluidPressure"
    qos_depth: 10
  - name: "/illuminance"
    type: "sensor_msgs/msg/Illuminance"
    qos_depth: 10
  - name: "/image_raw"
    type: "sensor_msgs/msg/Image"
    qos_depth: 10
  - name: "/imu"
    type: "sensor_msgs/msg/Imu"
    qos_depth: 10
  - name: "/joint_state"
    type: "sensor_msgs/msg/JointState"
    qos_depth: 10
  - name: "/joy"
    type: "sensor_msgs/msg/Joy"
    qos_depth: 10
  - name: "/joy_feedback"
    type: "sensor_msgs/msg/JoyFeedback"
    qos_depth: 10
  - name: "/joy_feedback_array"
    type: "sensor_msgs/msg/JoyFeedbackArray"
    qos_depth: 10
  - name: "/laser_echo"
    type: "sensor_msgs/msg/LaserEcho"
    qos_depth: 10
  - name: "/scan"
    type: "sensor_msgs/msg/LaserScan"
    qos_depth: 10
  - name: "/magnetic_field"
    type: "sensor_msgs/msg/MagneticField"
    qos_depth: 10
  - name: "/multi_dof_joint_state"
    type: "sensor_msgs/msg/MultiDOFJointState"
    qos_depth: 10
  - name: "/multi_echo_scan"
    type: "sensor_msgs/msg/MultiEchoLaserScan"
    qos_depth: 10
  - name: "/nav_sat_fix"
    type: "sensor_msgs/msg/NavSatFix"
    qos_depth: 10
  - name: "/nav_sat_status"
    type: "sensor_msgs/msg/NavSatStatus"
    qos_depth: 10
  - name: "/point_cloud"
    type: "sensor_msgs/msg/PointCloud"
    qos_depth: 10
  - name: "/point_cloud2"
    type: "sensor_msgs/msg/PointCloud2"
    qos_depth: 10
  - name: "/point_field"
    type: "sensor_msgs/msg/PointField"
    qos_depth: 10
  - name: "/range"
    type: "sensor_msgs/msg/Range"
    qos_depth: 10
  - name: "/region_of_interest"
    type: "sensor_msgs/msg/RegionOfInterest"
    qos_depth: 10
  - name: "/relative_humidity"
    type: "sensor_msgs/msg/RelativeHumidity"
    qos_depth: 10
  - name: "/temperature"
    type: "sensor_msgs/msg/Temperature"
    qos_depth: 10
  - name: "/time_reference"
    type: "sensor_msgs/msg/TimeReference"
    qos_depth: 10
